### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by gr8pefish** [ChatFawkes/Flux-Galaxy#77] opened 2015-02-18 04:14 UTC
Hey, first off I must say I really like the modpack! I am progressing significantly slower than I usually would and I am enjoying it a lot. Currently on the recommended version (0.7.14).

I haven't done much with servers before, but how should I go about updating them? Client is easy enough, just use the launcher, but server is a little more tricky. Should I just delete the mods/config folders and add in the newly downloaded folders, or is there a better way? (with additional mods that delete/replace method could get annoying)

Bugs/Tweaks:
Trying to see what limestone does in NEI causes a crash (Tinker's Steelworks)
Moss/TE metal's on TiCon tools don't work (already a known issue)
You might want to nerf the recipe on the atomic disassembler, it is very good for the default cost. 

These are the mods I added to my instance, you may want to consider adding some or all of them to the main pack:
iBench - Portable crafting table, lightweight and nifty mod.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2305252-ibench-portable-crafting-table

Iron Backpacks - Another smaller mod that adds upgrade-able backpacks with modular functionality (better than Forestry, TE, and BluePower's packs IMHO). http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2331340-iron-backpacks

Aroma Core/Aroma Backup - server backup tool (you should probably add this to the server instance)
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287828-aroma1997s-mods-betterchests-mining-world-mod

Malisis Core/Malisis Doors - Amazing doors and a very nice aesthetic block mixer
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2076338-1-7-2-1-7-10-forge-malisisdoors-1-7-10-1-4-3-23

Cheers, and keep up the good work!

**Comment by ChatFawkes** [comment] 2015-02-18 16:44
Hey thanks for the bug reports and suggestions!

I wasn't aware the Atomic Disassmebler was still in the pack (assumed it was part of Mekanism-Tools, which we don't have). I will look into "balancing" the recipe better if it needs to be done.

As for the mod suggestions, those are some good suggestions and I will definitely be considering some of them when for 0.8.x. That version (0.8.x) will mainly feature Thermal Dynamics (whenever it's released) and a frames mod (either Framez or Remain in Motion) in addition to some mods you and others have suggested. As I've said before I try not to add to many mods, so that server owners don't have to worry about bugs they cause and I don't want to bloat out the pack too much.

Also Ztones adds a little item called the Ofanix which provides portable crafting.

I will look into the bug related to NEI and limestone and will close this issue when that is resolved.

**Comment by gr8pefish** [comment] 2015-02-18 17:05
I also forgot. This is not a large deal, but you can only separate project red's red alloy wires with microblocks from immibis' microblocks, which isn't included. Bluepower teslatite wires can be separated with forge microparts, and they act as a less featured but viable alternative.

**Comment by ChatFawkes** [comment] 2015-02-18 17:14
I think you meant RedLogic xD. Also yah I will see about adding Immibis Microblocks (I think the microblocks are disabled by default in NEI, that's my main concern). BluePower also has red alloy wire, but those seem to be disabled and the rest of the mod is not in the most stable condition which is why I added RedLogic a while back. Thanks for the suggestion (that will probably go into the next 0.7.x latest/dev version)

**Comment by gr8pefish** [comment] 2015-02-20 03:46
Can I request a modtweaker recipe? Lapis/Redstone Blocks + pulverizer = 9 lapis/redstone. There is no way to convert from block to gem currently.

**Comment by ChatFawkes** [comment] 2015-02-20 03:47
Huh you can't do it in a shapeless recipe? If not, then I will add it.

**Comment by gr8pefish** [comment] 2015-02-20 03:48
Yeah it isn't there, I think some mod must disable it.

**Comment by ChatFawkes** [comment] 2015-02-20 03:49
You're trying this on 0.7.17a? Just want to know so I can try to replicate it myself.

**Comment by ChatFawkes** [comment] 2015-02-20 03:56
Seems to be working for me:
[Lapis](https://www.moddedmc.net/upload/2015-02-19_22-55-15.mp4)
[Redstone](https://www.moddedmc.net/upload/2015-02-19_22-56-09.mp4)

**Comment by gr8pefish** [comment] 2015-02-20 03:58
Oh you are right, it just wasn't showing in NEI, sorry!

**Comment by ChatFawkes** [comment] 2015-02-20 04:07
Also can you provide that crash you had with limestone in NEI? I can't seem to reproduce it.

**Comment by gr8pefish** [comment] 2015-02-20 04:09
Hmm that must have been fixed since the last time, it isn't giving an error for me anymore. That's nice!

**Comment by ChatFawkes** [comment] 2015-02-20 04:10
Okay I've taken your mod suggestions into account, so I'll be closing this issue for now. Thanks for the bug reports and feedback!

**Comment by gr8pefish** [comment] 2015-02-20 23:48
I know you closed this issue but I wanted to post here in case I was just being dumb. Using v 7.17 and I cannot find any of the extra utilities upgrades (ex: world interaction), they simply appear to not exist.

**Comment by gr8pefish** [comment] 2015-02-21 04:43
Okay sorry, the upgrades have reappeared. I didn't change anything, that was a strange bug.

Not sure if you saw my edit on the previous post about the salt.

**Comment by ChatFawkes** [comment] 2015-02-21 04:44
Yah I know about that, but I just left it around though.

**Comment by ChatFawkes** [comment] 2015-02-21 04:45
on a sidenote can you hop on IRC? http://irc.lc/synirc/moddedmc/mmcuser@@@

**Closed** 2015-02-21 05:02 UTC
Labels: crash, enhancement, mod bug
