### ISSUE TITLE
Crash that I can't figure out

### ISSUE THREAD

**Issue by sharef88** [ChatFawkes/Flux-Galaxy#66] opened 2015-01-01 01:05 UTC
Crash-Report generated by the server.
http://pastebin.com/k9z2X98f
I had placed a small compact machine about 30m before this crash.  I was removing some mechanisim universal cable with an unenchanted bound pickaxe about 10 blocks away from said compact machine. The machine was inert and empty.  I cant figure out how to fix this.  MCEdit surgery didn't help the matter, nor did removing compact machines mod, or the related file in data/ or the dim.
I'm using pack version 7.3.

**Comment by ChatFawkes** [comment] 2015-01-02 03:30
Can you give me a copy of the crash report?

**Comment by sharef88** [comment] 2015-01-02 17:53
Full-Crash report from FG/crash-reports/
http://pastebin.com/Wdhe5pbm

**Comment by ChatFawkes** [comment] 2015-01-12 07:22
Hey can you repeat this crash again with the latest version of the pack (0.7.9)?

**Comment by sharef88** [comment] 2015-01-12 17:06
Unfortunately, it nuked my map.  some part of the map that my Forge Essentials backups don't back up.

**Comment by ChatFawkes** [comment] 2015-01-13 04:42
Hmm I guess I'll just close the issue for now because we don't know enough to confirm if it was a bug with Compact Machines. If you do manage to reproduce it then just comment on this issue and I'll re-open it.

**Closed by ChatFawkes** 2015-01-13 04:42 UTC
Labels: crash
